# Dependencies
markdown:         kramdown
highlighter:      rouge # changed from `pygments` as github says so

# Permalinks
permalink:        pretty

# Setup
title:            'Fredi Quispe H.'
tagline:          'PhD student at the Observatorio Nacional of Rio de Janeiro'
description:      ''
url:              https://fredifqh.github.io
baseurl:          ''
paginate:         5
paginate_path:    '/blog/page:num/'

author:
  name: 'Fredi Quispe H.'
  email: 'fredifqh[at]gmail.com'
  github: fredifqh
  bio: PhD student at the Observatorio Nacional of Rio de Janeiro
